# Generated by Django 3.1.7 on 2021-03-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrdName', models.CharField(max_length=50, verbose_name='Product Name')),
                ('PrdDesc', models.TextField(verbose_name='Product Description')),
                ('PrdPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Price')),
                ('PrdCost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Cost')),
                ('PrdCreated', models.DateTimeField(verbose_name='Product Created')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
