# Generated by Django 3.1.7 on 2021-03-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PrdCost',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Product Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PrdPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Product Price'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProImage', models.ImageField(upload_to='product', verbose_name='imge')),
                ('PrdIProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
