# Generated by Django 3.1.7 on 2021-03-29 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210329_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatName', models.CharField(max_length=50)),
                ('CatDesc', models.TextField(verbose_name=' Category Description')),
                ('CatImg', models.ImageField(upload_to='category/')),
                ('CatParent', models.ForeignKey(blank=True, limit_choices_to={'CatParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categoreis',
            },
        ),
    ]
