# Generated by Django 3.1.7 on 2021-03-29 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210329_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParoductAccessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParAccessories', models.ManyToManyField(related_name='Accessories_product', to='product.Product', verbose_name='Accessories')),
                ('PrAccProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_Accessories', to='product.product')),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
            },
        ),
    ]
