# Generated by Django 3.1.7 on 2021-03-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_paroductaccessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paroductaccessories',
            name='PrAccProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_Accessories', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productalternative',
            name='ProAlnProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productalternative',
            name='proAlAlternative',
            field=models.ManyToManyField(related_name='alternative_product', to='product.Product', verbose_name='Alternative'),
        ),
    ]
