# Generated by Django 3.1.7 on 2021-03-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_variant'),
        ('product', '0008_auto_20210329_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PrdBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='PrdCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
