# Generated by Django 3.1.7 on 2021-03-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210331_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProImage',
            new_name='PrdImage',
        ),
    ]
