# Generated by Django 3.1.7 on 2021-04-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210331_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Prdslog',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
