# Generated by Django 3.1.7 on 2021-04-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_prdslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Prdslog',
            new_name='Prdslug',
        ),
    ]
