# Generated by Django 3.1.7 on 2021-04-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210404_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PrdDescountPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Product Descount Price'),
            preserve_default=False,
        ),
    ]
